### ISSUE TITLE
laststatus=2 maybe not a super default

### ISSUE THREAD

**Issue by zelurker** [tpope/vim-sensible#102]
it removes 1 line from the screen, and the only advantage is the indicator to show if the file has been saved which can be retrieved by other ways. I have put that back to 1 in my defaults.

**Comment by vheon** [comment]
> the only advantage is the indicator to show if the file has been saved

or if the file is read only; or if the file has been recognized with the right filetype; or if the encoding is the right one; or ...

**Comment by justinmk** [comment]
And CTRL-G to check which file you're editing gets annoying. I tried laststatus=1 for a couple weeks and found it not worth the hassle.

**Comment by tpope** [comment]
All of the above plus personally think it looks weird when it appears/disappears upon splitting. Gone file this under defaults "everyone" agrees on.

**Comment by zelurker** [comment]
I don't really care actually, I just filled this because in the readme it's
said you'd like to know if we change a setting from yours, so it's the case
here.
I can also add that if you use flagship.vim, then the status bar is
automatically enabled in this case without having to touch this setting,
which makes sense here since it adds some features.
Another reason for me not to touch laststatus !

2015-09-24 20:58 GMT+02:00 Tim Pope <notifications@github.com>:

**Comment by twome** [comment]
I need as much space on my screen as possible (tiny laptop, no money) and this default, for some reason, isn't letting me override it by adding `set laststatus=0` to my `~/.config/nvim/init.vim` after the `vim-plug` section. This is super annoying! I already get filenames from my terminal's tab titles, I already get line numbers from `:set number`/`Ctrl+g`, I never use any encoding other than UTF-8, it's easy to notice if the filetype's wrong etc.

I'm using NeoVim, and `vim-plug` to install `sensible`. 
Commenting out `Plug 'tpope/vim-sensible'` fixes the issue.

Thanks; I appreciate all the work you've done.

**Comment by alphatroya** [comment]
Neovim recently introduced a [global statusline](https://github.com/neovim/neovim/pull/17266). I think 2 option is not appropriate default for it.

**Comment by lithammer** [comment]
> Neovim recently introduced a [global statusline](https://github.com/neovim/neovim/pull/17266). I think 2 option is not appropriate default for it.

Why wouldn't `laststatus=2` be an appropriate default? It's what Neovim itself defaults to after all.

**Comment by alphatroya** [comment]
I mean that for neovim users 2 will be not be the preferred option after all. And not anyone from them will agree to that default.
