### ISSUE TITLE
Different mapping for clearing search highlight

### ISSUE THREAD

**Issue by janek-warchol** [tpope/vim-sensible#104]
sensible.vim maps C-L to clearing highlight.  I find this quite unintuitive.  What about mapping it to Esc in normal mode?  Like this:

``` vim
" Clear highlighting on escape in normal mode
nnoremap <silent> <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[
```

**Comment by tpope** [comment]
I don't buy that escape (which normally means leave insert mode, or cancel), is more intuitive than C-L (which means "redraw screen", both in vim and outside of it e.g. in most shells). But the absolute deal breaker is that remapping escape can cause nasty interference with other escape sequences like the arrow keys.

**Comment by janek-warchol** [comment]
Fair enough.  Thanks for quick answer.
