### ISSUE TITLE
neovim + tmux + :set ttimeout causes weird characters after <Esc>

### ISSUE THREAD

**Issue by giraj** [tpope/vim-sensible#105]
Just thought I'd note this somewhere for people to find.

Experienced [this bug](https://github.com/neovim/neovim/issues/2017) which inserts strange characters after pressing ```<Esc>``` (and continuing as in if normal mode quickly thereafter) in Neovim under tmux. Solution was to configure tmux with ```set -s escape-time 0```.

After installing ```vim-sensible``` the bug reocurred, again solution is to ```:set nottimeout```.

**Comment by vheon** [comment]
Neovim has included most of vim-sensible settings as a default, so I don't think that a Neovim user should install vim-sensible at all.

**Comment by giraj** [comment]
You're probably right - I wasn't thinking far enough. Thanks!

**Comment by tpope** [comment]
"Most" != "all", and to the extent that I use Neovim, I'm not going to maintain a distinct config for it. But my reading is that this is a bug in Neovim, correct? Maybe we just wait it out?
