### ISSUE TITLE
Turn off auto-newline

### ISSUE THREAD

**Issue by Zekario** [tpope/vim-sensible#108]
The auto-newline messes up pasting. I can't put an example here, as Github's formatting won't let me. Basically, when I paste with this plugin on, a space before characters on each line is addest to the next. If there is already a space, it gets added to it. This leads to, for example, having 4 spaces in front of the first line, and 8 before the second if the next line already had 4 spaces.

As I said, disabling this plugin stops this, but breaks my other plugin, airline. I use Vundle for plugins.

**Comment by justinmk** [comment]
Use `:set paste` (built-in) or `yo` (from https://github.com/tpope/vim-unimpaired)

**Comment by tpope** [comment]
I started to refute this but I'm not even sure what I'm arguing against, as there is no "auto-newline" option.  Suffice to say that the only way to completely "fix" this is to disable **all code formatting**, and that's not going to happen. `:set paste` is indeed a universal solution, or you can paste with the GUI subsystem if that's available `"+p`/`"*p`.

**Comment by Zekario** [comment]
Sorry! I'm not an expert at vim, and noticed that it didn't appear to happen with this disabled. I'll use `:set paste`, thanks!

**Comment by tpope** [comment]
Be advised `:set paste` is a *temporary* option. If you leave it permanently enabled you'll be using a seriously neutered Vim.
