### ISSUE TITLE
CTRL-L: include `syntax sync fromstart`

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-sensible#111]
`syntax sync fromstart` is often useful when syntax highlighting gets out of whack. How do you feel about this:

    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><Bar>syntax sync fromstart<CR><C-L>

**Comment by tpope** [comment]
That's a permanent change to the buffer with potentially disastrous performance implications. And if you're okay with that, why not just enforce it globally rather than tack it onto a distantly related map?

**Comment by justinmk** [comment]
Yeah I didn't think this through, but based on the output of `:syntax sync` it is not globally permanent, only per-buffer.
