### ISSUE TITLE
Ignorecase just for command line

### ISSUE THREAD

**Issue by mtglsk** [tpope/vim-sensible#112]
Really sucks to not have it set when searching for custom commands, example:

**set noignorecase**
`:gbl <tab> <tab>` .... nothing happens

**set ignorecase**
`:gbl <tab><tab>` .... becomes `:Gblame`

With smartcase it is even better.

**Comment by tpope** [comment]
There's no way to set it just for the command line, and I'm definitely not setting it globally.

**Comment by junkblocker** [comment]
FYI, this seems to work but is too radical a mapping

```vim
nnoremap : :call IgnoreCase()<CR>:
function! IgnoreCase()
    set ignorecase
endfunction
nnoremap / :call NoIgnoreCase()<CR>/
function! NoIgnoreCase()
    set noignorecase
endfunction
```
