### ISSUE TITLE
What completeopt do people use?

### ISSUE THREAD

**Issue by mtglsk** [tpope/vim-sensible#116]
Do people change this? I find the default autoselection extremely irritating (`menu, preview`). It's really not that obvious for a newcomer to know how to cancel a selection (and vim's omnicomplete is quite complicated as it is) so you tend to BS through the change and then go google on how to cancel a completion ;). Most ide's etc. show the balloon but don't autoselect a completion unless you want to (like ctrl space to show completions, then ctrl space again to autocomplete).

I personally use `noselect, menuone, preview` but something like `completeopt+=longest` is also imho better than default.

**Comment by tpope** [comment]
That's a pretty good example of why the editors in most IDEs are a joke tbh. You want to add an extra keystroke to *every single completion* just so someone doesn't have to learn how to cancel an insertion?
