### ISSUE TITLE
How have you decided which options to check compatibility for?

### ISSUE THREAD

**Issue by jmz-b** [tpope/vim-sensible#118]
For example, you do
 
```viml
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif
```
which checks if vim was compiled the syntax feature. 

Yet you don't do

```viml
if has('cmdline_info')
  set ruler
endif
```

What was the reasoning behind this decision?

**Comment by tpope** [comment]
It's generally just based on whether I've run into a version of Vim without that feature (but that still has plugin support). In the syntax case in particular, I probably just bolted on the feature check because I was already doing the `g:syntax_on` check anyways.

**Comment by jmz-b** [comment]
Thanks for answer =]
