### ISSUE TITLE
Properly display man pages in GUI

### ISSUE THREAD

**Issue by aidecoe** [tpope/vim-sensible#120]
``` vim
runtime ftplugin/man.vim
if has("gui_running")
    nnoremap K :<C-U>exe "Man" v:count "<C-R><C-W>"<CR>
endif
```

**Comment by aidecoe** [comment]
Actually I see no reason why not do it for Vim as well:

```
runtime ftplugin/man.vim
nnoremap K :<C-U>exe "Man" v:count "<C-R><C-W>"<CR>
```

it makes browsing man pages much more convenient.

**Comment by mtglsk** [comment]
I find no problems with browsing man pages with less, most vi keys / inc search are there and it's not like i'm going to edit them anyway.

**Comment by tpope** [comment]
Yes to enabling the `:Man` command, no to overriding `K` by default.

FYI, recent versions of Vim allow you to do `:set keywordprg=:Man`.

**Comment by Konfekt** [comment]
Wouldn't on `has(win32)` still DOS's `help` or a command such as `command! -nargs=1Help silent exe 'term ' . '<args> /?'` be arguably just as useful?

**Comment by tpope** [comment]
"Load a manpage into a Vim buffer" and "blindly run a command in the terminal with `/?` appended" are not in the same category of usefulness, imo. One provides an abstraction, the other just saves you typing out a few characters. And it only works with `cmd.exe`, which is increasingly falling out of fashion.

**Comment by Konfekt** [comment]
But which manpage in `win32` (but not `win32unix`)? On `cmd` there is `help`,  on `powershell` there is `Get-Help`.

**Comment by Konfekt** [comment]
Looking at `man.vim`, the buffer seems to be loaded by 

```vim
" autoload/dist/man.vim (lines 90-99)
func s:FindPage(sect, page)
  let l:cmd = printf('man %s %s', s:man_find_arg, s:GetCmdArg(a:sect, a:page))
  call system(l:cmd)

  if v:shell_error
    return 0
  endif

  return 1
endfunc
```

Even if `cmd` is out of fashion, likely many installations of (g)Vim use it as a default shell on `win32`.

**Comment by tpope** [comment]
For `:Man`, all I am doing is loading Vim's built-in implementation. For `:Help`, you're asking me to provide the implementation. I don't want to maintain the implementation. I don't want to support the implementation. This has nothing to do with sensible.vim.

**Comment by Konfekt** [comment]
Sensible.vim should improve on the defaults also on `win32` which used to be `help` on `&shell=cmd` and now is `Man`. For the average `win32` user, `help` is yet a more sensible default (if @goweol did not already implement Man as Get-Help/help on Powershell and Cmd).
