### ISSUE TITLE
No to 2 spaces after period

### ISSUE THREAD

**Issue by aidecoe** [tpope/vim-sensible#122]
Does anyone still add two spaces after period? By default Vim inserts two spaces after a '.', '?' and '!' with a join command (and reformat). Why it is default?

```vim
set nojoinspaces
```

**Comment by tpope** [comment]
I do.

http://stevelosh.com/blog/2012/10/why-i-two-space/

**Comment by justinmk** [comment]
@aidecoe The Vim help itself uses 2 spaces, which explains the origin of the default setting. I myself was never convinced by Losh's apologia.

**Comment by aidecoe** [comment]
@tpope Thanks for pointing to the article. That's quite good +1 for two spaces.

@justinmk Yes, that explains default settings, thanks!
