### ISSUE TITLE
can pull the repo

### ISSUE THREAD

**Issue by kakulukia** [tpope/vim-sensible#123]
I tried on multiple computers and am not able to download the repo either with git or https.

GIT:
Cloning into 'vim-sensible'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

HTTPS:
fatal: unable to access 'https://github.com/tpope/vim-sensible.git/': transfer closed with outstanding read data remaining

Whats up with the repo?

**Comment by mtglsk** [comment]
Cloning into 'vim-sensible'...
    fatal: unable to access 'https://github.com/tpope/vim-sensible/': transfer closed with outstanding read data remaining

**Comment by justinmk** [comment]
Must be on GitHub's end, should be reported to them.

**Comment by evantravers** [comment]
Same.

**Comment by ernstki** [comment]
This was also affecting the ability to download the .zip file of `master`. Seems to have resolved itself as of 0730 UTC, 2016-04-26, at least with whatever servers I'm talking to over here.

**Comment by kakulukia** [comment]
confirmed its working again!
