### ISSUE TITLE
Relatively slow to load

### ISSUE THREAD

**Issue by boompig** [tpope/vim-sensible#126]
This is my slowest plugin to load. Output of `vim-profiler.py`:

```
$ python vim-profiler.py -r 5 -s
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/dbkats/.vim/plugged
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/dbkats/.vim/plugged
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/dbkats/.vim/plugged
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/dbkats/.vim/plugged
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/dbkats/.vim/plugged
====================================
Top 10 plugins slowing vim's startup
====================================
1    38.044   *filetype.vim
2    37.456   vim-sensible
3    27.478   *synload.vim
4    13.747   vim-buftabline
5     6.706   nerdcommenter
6     4.730   vim-unimpaired
7     4.479   lightline.vim
8     3.499   *syncolor.vim
9     2.951   emmet-vim
10    1.459   *netrwPlugin.vim
====================================
```

Is there any way to make it faster on load?

**Comment by vheon** [comment]
That is probably because of [this line](https://github.com/tpope/vim-sensible/blob/9e91be7e0fb42949831fe3161ef583363648aa58/plugin/sensible.vim#L12) which unless you don't use `ftplugin`s you still want in your vimrc.

**Comment by boompig** [comment]
`filetype.vim` is slow itself, but I mean just the portion for `vim-sensible`.

**Comment by vheon** [comment]
If you profile like this:

```bash
vim --cmd 'profile start vim.profile' \
     --cmd 'profile func *'                 \
     --cmd 'profile file *'                 \
     -c 'profdel func *'                    \
     -c 'profdel file *'                    \
     -c 'qa!'
```

you will get a vim.profile file and in there there will be the times for every line of vimscript.

**Comment by tpope** [comment]
Try putting `filetype plugin indent on` in your vimrc and see if that affects the result.

**Comment by tpope** [comment]
Oh, and `syntax enable` or `syntax on`, if you don't already have that.

**Comment by boompig** [comment]
@tpope Actually it's much slower when those lines added. You can see my full .vimrc here: https://github.com/boompig/dotfiles/blob/master/vimrc.

I add `filetype off` and `filetype plugin indent off` before loading plugins, then `filetype plugin indent on` and `syntax on` further in the vimrc. Does the order matter?

**Comment by tpope** [comment]
I don't know the details of your plugin manager of choice but order can definitely matter. Make sure you turn both settings on before loading sensible.vim.

**Comment by idbrii** [comment]
> Make sure you turn both settings on before loading sensible.vim.

`filetype plugin indent on` is slow every time you run it (you can see so interactively), so doing it in vimrc and sensible slows down startup. However, using pathogen, sensible (in ~/.vim/bundle/sensible) is loaded after several other plugins which modifies their behaviour.

Checking g:did_load_filetypes appears to work:

```
if has('autocmd') && !exists('g:did_load_filetypes')
  filetype plugin indent on
endif
```

```
gvim -Nu ~\.vim\bundle\sensible\plugin\sensible.vim -U NONE
:filetype
" see that they're all ON
" remove the filetype line from sensible and repeat the above and see that some are OFF
```

However, I don't understand that variable and it's not documented.

Alternatively, should sensible more strongly encourage users to load it at the start of their vimrc? Or tell their package manager to load it first?

**Comment by tpope** [comment]
> `filetype plugin indent on` is slow every time you run it (you can see so interactively), so doing it in vimrc and sensible slows down startup.

I can't see this at all. When I time it I get 7 milliseconds, which is about 1 frame on a 144 Hz display. Like most people I have a much slower 60 Hz display.

However I can't see much downside to a proper short circuit (which also requires checking `g:did_load_ftplugin` and `g:did_indent_on`), so I am tentatively rolling this out.
