### ISSUE TITLE
Sidescrolloff pre-condtion does not allow 0 value

### ISSUE THREAD

**Issue by cmcginty** [tpope/vim-sensible#129]
The logic for setting `sidescrolloff` does not allow for a value of 0. The gist of the check is to let the user override the default value in vim-sensible, but when the user value is "0", the vim-sensible default is set. So how should it allow for the user to keep the value set to 0?

```vim
if !&sidescrolloff
  set sidescrolloff=5
endif
```

**Comment by idbrii** [comment]
See #95 for why scrolloff>0 is a sensible default.

> The gist of the check is to let the user override the default value in vim-sensible

No. Check prevents cobbering greater values. See #26.

See [FAQ](https://github.com/tpope/vim-sensible#faq) for how to override a setting.

**Comment by cmcginty** [comment]
I agree with `scrolloff` comments. I just don't think it applies to `sidescrolloff`. I don't think the viewport should be jumping left/right unless going off the screen. Having an extra 5 chars to the right of your cursor when your typing is not helpful contextually.

**Comment by tpope** [comment]
I'm pushing an experimental change that attempts to Do The Right Thing when overriding an option in your vimrc.

Regarding `'sidescrolloff'` in particular, I must admit I have `'wrap'` enabled 99% of the time. While I do think a bit of surrounding context can occasionally be helpful for balancing parentheses, etc., the default value of `'sidescroll'` makes the cure worse than the disease. So see #124. I'll make a decision on that front soon.
