### ISSUE TITLE
isnt it a good idea to have "set ic" in vim-sensible?

### ISSUE THREAD

**Issue by raghav135** [tpope/vim-sensible#132]
I feel it is very frequently used.

**Comment by tpope** [comment]
I don't see it plainly laid out in any of those issues so I'll do it here. `'ignorecase'` is a garbage umbrella option that affects everything from regex searches to command line tab complete to VimL to `<C-X>` insert mode complete. That last one is a particular sore spot for me, as I can't stand `fo<C-p>` completing to `Foo` and not `foo`. I would honestly sooner add `nnoremap / /\c` than `:set ignorecase`.
