### ISSUE TITLE
Setting shell to bash

### ISSUE THREAD

**Issue by swyckoff** [tpope/vim-sensible#133]
I may be misunderstanding the conditional on https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L64 due to not knowing vimscript but my ":echo &shell" is "/bin/zsh". I am not so sure I want to override that on https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L65.  Perhaps I should override it but I don't know the reason why.

**Comment by deiga** [comment]
Well it seems to only set shell to bash when the shell is fish

**Comment by swyckoff** [comment]
Totally accurate. My bad.
