### ISSUE TITLE
Sensible deprecated?

### ISSUE THREAD

**Issue by 0matgal0** [tpope/vim-sensible#137]
Now that vim has https://github.com/vim/vim/blob/master/runtime/defaults.vim, does it mean that vim-sensible is deprecated?

**Comment by 0matgal0** [comment]
I think a good idea would be to source from defaults.vim (if available) and then set all else which sensible adds?

**Comment by tpope** [comment]
Short answer is no. While defaults.vim is better than I expected, there are enough meaningful differences between the two that I don't see us as deprecated.

Regarding your suggestion, what exactly do we do if defaults.vim *isn't* available? Vim 8 is only 6 months old. And what does this level of indirection buy us other than the ability to delete a dozen or so lines that never really change and don't require active maintenance?

**Comment by ELLIOTTCABLE** [comment]
I've got no horse in this race, but coming across this issue and reading your response, @tpope, I'd say it really just gives you one thing:

If the upstream vim-community decides on a new default (however unlikely that may be, and however-much *less* likely it is that you don't notice it and follow along here), all ‘sensible’ users will automatically be using it.

Just a thought. `¯\_(ツ)_/¯`

**Comment by tpope** [comment]
Well yeah, but `defaults.vim` only loads when there's no vimrc, so that's not the scenario we're in.

I'm actually kind of happy about defaults.vim, because now I can be a teensy bit more opinionated without leaving users in the cold. I really wish it didn't have that "jump to last known cursor position" feature though. I personally favor the predictability of starting on line 1.

**Comment by kiryph** [comment]
For people who are happy with [defaults.vim](https://github.com/vim/vim/blob/master/runtime/defaults.vim) but do not like "jump to last known cursor position", consider following:

```
source $VIMRUNTIME/defaults.vim
" Remove autocmd 'jump to last known cursor position'
augroup vimStartup | au! | augroup END
```

**Comment by tpope** [comment]
`autocmd! vimStartup` works too.

**Comment by hholst80** [comment]
I 

> ^ Yup, especially when you can easily just type `'"` to get to the last known cursor position if you really want to.

That is a non-argument I would say because it is as easy to jump to line 1 if you really want to.

The question is what is the most sensible default? To start at the last known position or at line 1? Should vim hold state on files?
