### ISSUE TITLE
Alt-key choke when nottimeout on neovim

### ISSUE THREAD

**Issue by xeyownt** [tpope/vim-sensible#141]
Since commit b6033cb, I again have issue with choking Alt-key combinations in neovim.
Most of the time they work fine, but sometime they are ignored.

Contrary to all issues reported here, I actually kept vim-sensible in my plugins precisely because it was setting ttimeout and ttimeoutlen=100, so I wonder why this change?

**Comment by tpope** [comment]
Some context is at https://github.com/neovim/neovim/issues/1202. I don't really know the specifics, but I can confirm that _I_ haven't needed it on Neovim.
