### ISSUE TITLE
Suggestion: set synmaxcol to sane levels

### ISSUE THREAD

**Issue by oblitum** [tpope/vim-sensible#142]
Hey, just wanted to suggest setting `synmaxcol` to a _sensible_ level, it's 3000 by default!, and this makes no sense.

I learned of it while talking on #vim how editing an HTML with minified CSS line completely slowed everything down. As it's not sane to have human content reach this limit, I think bringing this value down to 300 or something is better than having it at 3000.

**Comment by trevordmiller** [comment]
Agreed, this would be a nice setting to add that seems like it wouldn't do any harm

**Comment by ruifm** [comment]
I have it set to 240 (3*80) and it is more than enough.

**Comment by tpope** [comment]
That's not "more than enough" if you edit VimL. I could probably be convinced to compromise at 500.

**Comment by oblitum** [comment]
> That's not "more than enough" if you edit VimL. I could probably be convinced to compromise at 500.

Maybe having a reasonably short length for all files with a slightly larger length for some exceptional filetypes known to have wider sources?

**Comment by oblitum** [comment]
Ops, closed by accident.

**Comment by tpope** [comment]
I'm not going to curate `synmaxcol` for individual file types.

**Comment by oblitum** [comment]
@tpope no need, reason why I deleted the message a sec before sent, it was not supposed to be sent at all :-/

**Comment by ruifm** [comment]
> That's not "more than enough" if you edit VimL. I could probably be convinced to compromise at 500.

Still better than 3000. I would go for that.
Out of curiosity is syntax highlighting even useful when editing beyond a 500 charatecter long line?

**Comment by trevordmiller** [comment]
Thanks! One less thing in my vimrc 🎉 https://github.com/trevordmiller/dotfiles/commit/03738e35b1d493bff69d159bca9c9b9559b0247a

**Comment by oblitum** [comment]
It's great... but I'll keep my 250 setting :)

**Comment by oblitum** [comment]
Weird trivia, c176d13 is from 2018 o_O

**Comment by tpope** [comment]
Shhhhh

**Comment by tengucrow** [comment]
Hello, from 2019. I use Vim for a wide range of tasks - not only as an IDE. Therefore, I was surprised a lot when my quotes and other settings in the texts, where the paragraph is a single long line, began to highlight only 500 characters from the beginning of the line. Since the setting is deeply hidden enough - it took some time to find the name itself and who exactly changed it. Maybe it makes sense to add information on this setting in the readme - to increase the explicitness?

**Comment by tpope** [comment]
Nah, I'd rather revert. This never sat right with me.

**Comment by trevordmiller** [comment]
Sad this got reverted. I'm experiencing much slower vim speeds since. Manually adding a lower  `synmaxcol` makes things speedy again so I'll do that on my end now that it is no longer in vim-sensible.

**Comment by Asheq** [comment]
If you frequently work with prose having long paragraphs on a single line, then having a large synmaxcol value is helpful. Here's a single wrapped line in markdown with synmaxcol set to just 500. Notice the bold highlights begin to stop showing halfway through the paragraph/line:

![image](https://github.com/tpope/vim-sensible/assets/4657140/a35ec832-e7d1-4fa7-960e-f33401cc08b5)

If performance with the default synmaxcol is a problem, it should probably be improved in vim itself. Also, minified CSS files and such that are not meant for human consumption/editing should not be opened anyway. On the off occasion that they need to be opened, you can always set synmaxcol to a lower value for just that file: `edit +setlocal\ synmaxcol=500 file.md`
