### ISSUE TITLE
Suggestion: include common split movement

### ISSUE THREAD

**Issue by trevordmiller** [tpope/vim-sensible#146]
It seems to me that many vimmers have this easier split navigation:

```
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
```

I feel it would be nice to have this in vim-sensible since it wouldn't hurt those who don't use it but would remove the need for many other vimmers to define it repeatedly in their .vimrc

**Comment by tpope** [comment]
I use `<C-L>` for the built-in redraw behavior plus `:nohlsearch`, so it would definitely hurt me.

Personally I find thinking about windows geometrically to be way too much cognitive overhead, and favor `<C-J>` and `<C-K>` for the simple cycling behavior of `<C-W>w` and `<C-W>W`. But I don't think I can get away with imposing that.

**Comment by trevordmiller** [comment]
Ah good point, didn’t think about c-l. Thanks!
