### ISSUE TITLE
Suggestion: persist history

### ISSUE THREAD

**Issue by trevordmiller** [tpope/vim-sensible#147]
Would there be any opposition to adding something like this:

```
set undofile
set undodir=~/.vim/undo_files//
set directory=~/.vim/swap_files//
set backupdir=~/.vim/backup_files//
```

To persist history in a way that doesn't get in the way?

**Comment by tpope** [comment]
I had this in the initial version but yanked it because everyone disagreed about what directory to put the files in.

**Comment by trevordmiller** [comment]
I wonder if this would be worth exploring again? It seems to me that no-one would oppose to having persisted history if a directory name could be agreed on?

**Comment by tpope** [comment]
For starters, I don't want them in `~/.vim` because that interferes with the `scp -r .vim remotehost:` use case.

**Comment by trevordmiller** [comment]
Would another directory make sense?

**Comment by buzuck** [comment]
Maybe using `$XDG_CACHE_HOME` if defined would make some sense here? And this would be something easily customizable by everyone.

**Comment by tpope** [comment]
I had this at one point and it was pointed out that cache expiry shouldn't delete your history.

**Comment by buzuck** [comment]
Good point! I'm moving my history to $XDG_DATA_HOME then :)
