### ISSUE TITLE
sessionoptions+=localoptions

### ISSUE THREAD

**Issue by Asheq** [tpope/vim-sensible#153]
What do you think about adding `sessionoptions+=localoptions`?

In the absense of `options` (due to `sessionoptions-=options`, it seems to be very helpful when loading a session. Things like local `number` or `warp` are remembered. I also noticed that help files  are actually remembered as being help files rather than any old file ([Help][RO] shows up in the statusline). 

Are there any downsides?

Thanks for your consideration!

**Comment by tpope** [comment]
I'm not sure. Turning it on I do see a lot of weird noise in the session file that I don't really want in there, but I'm not immediately noticing any practical downsides, and your point about help files is valid. I guess I will try it and see what happens.

**Comment by justinmk** [comment]
A downside is that if things get screwed up by a plugin, one may want to restart vim and return to a session without doing surgery on the session.

**Comment by tpope** [comment]
Yeah I do worry about that. Concrete examples of this happening would potentially sway me back. I'll keep an eye out as well.

**Comment by mg979** [comment]
Just wanted to say that I'm using a copy of sensible.vim that I don't update. I added this option since it wasn't in my copy and it screwed all of my sessions, adding weird buffer imap mappings. Probably a plugin has to do with it, but those weird mappings were only present after saving and reloading the session, not added in the middle of the session.

**Comment by tpope** [comment]
Nevermind, I forgot the documented fact that `localoptions` includes local mappings.

I do think this is probably going to get reverted. One can always add `localoptions` in their own vimrc if they so choose.

**Comment by mg979** [comment]
I did `:verbose imap <buffer>` when it happened, and it was the session that added those mappings. The strange thing was that before quitting vim the mappings weren't there, and they were 'created' by the session on reload.

**Comment by tpope** [comment]
Reverted.
