### ISSUE TITLE
Revert accidental <C-W>

### ISSUE THREAD

**Issue by brendanwhit** [tpope/vim-sensible#161]
You have the line to revert <C-U> in insert mode.  Just wondering why 
`inoremap <C-W> <C-G>u<C-W>`
is not included to revert accidentally deleting a word instead of the whole line.

**Comment by justinmk** [comment]
ctrl-w deletes small things, so it is not as dangerous as ctrl-u. 

Although, I almost never use ctrl-w in insert-mode, so I wouldn't find the extra undo steps too annoying. Maybe it's useful.

**Comment by tpope** [comment]
The older and clumsier my hands get the more this appeals to me. Let's try it.
