### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by jribbens** [tpope/vim-sensible#165]
The installation instructions include the line:

    vim -u NONE -c "helptags sensible/doc" -c q

This command fails with the following error message:

    Error detected while processing command line:
    E150: Not a directory: sensible/doc

I am using vim 8.0.1453.

**Comment by tpope** [comment]
Does said directory exist?

Do you have `'autochdir'` set?

**Comment by jribbens** [comment]
It does not exist - no file or directory exists anywhere in the filesystem with the name `sensible` except `/home/jon/.vim/pack/tpope/start/sensible`, and it does not contain anything called `doc`.

`autochdir` is not set, which is the default.
