### ISSUE TITLE
sidescrolloff setting causes sudden row offsets in vifm plugin in Neovim on Windows

### ISSUE THREAD

**Issue by fwy** [tpope/vim-sensible#170]
I recently started using the Vifm file manager with the vifm.vim plugin, and noticed some odd behavior when opening this plugin in Neovim on Windows.  When scrolling down a Vifm pane, the selected row jerks to the left or right, often cutting off the first few leftmost characters as shown here.

![image](https://user-images.githubusercontent.com/4481175/111549605-74182080-874a-11eb-84c5-fd8545f0da9a.png)

It works fine in Vim on Windows, and in both Neovim and Vim on Linux.

I traced the behavior down to this command in sensible.vim, which I have also been using for a long time now.

if !&sidescrolloff
  set sidescrolloff=5
endif

I am not familiar with sidescrolloff and have never had to manipulate it, but when it is left unset the problem does not occur.

I think this may be caused by some Neovim bug, but would it make sense to disable it in vim-sensible, or maybe to conditionally execute it if !has('nvim') and !has('win32")?

**Comment by tpope** [comment]
This indeed smells like a Neovim bug, and it didn't take me long to find an obvious candidate at https://github.com/neovim/neovim/commit/7b764bb43d9c45e04a8dbb0146b3529991007949.

Without more context, I don't think playing a game of disabling whack-a-mole makes sense. You can disable it yourself with the instructions in the README if you need to.
