### ISSUE TITLE
Insert mode <c-w> mapping breaks abbreviations

### ISSUE THREAD

**Issue by urbainvaes** [tpope/vim-sensible#177]
Hi Tim,

You might argue this is a bug with vim and not this plugin, but I'll explain anyway.

## Desired behavior

1) Open a new vim instance and buffer, typing `vim -u NONE` in terminal. 
2) Define `:iabbrev hw helloworld`.
3) Enter insert mode and type `hw ` (note the space at the end). This expands into `helloworld `.
4) Without leaving insert mode, type `<c-w>`. This brings us back to an empty line (and buffer).
5) Type (still in insert mode) again `hw `. This correctly expands into `helloworld `.

## Behavior with `<c-w>` mapping from `vim-sensible`:

1) Open vim as above, and then define `inoremap <C-W> <C-G>u<C-W>`.
2) Same as above.
3) Same as above.
4) Same as above.
5) Type again `hw `. This now **does not expand** into `helloworld `.

The same issue arises when trying to expand the abbreviation with `<c-]>`.

I know there is a `mapcheck` in your code, so this issue is not difficult to resolve for users who experience it, but I still think this behavior of `<c-w>` might be undesirable given the aim of this plugin.

Many thanks again for all your great work! :)

**Comment by tpope** [comment]
I don't think there's anything I can do about this. It doesn't seem worth removing the map over.
