### ISSUE TITLE
"set display+=lastline" do nothing if added after "set display=truncate"

### ISSUE THREAD

**Issue by john-cj** [tpope/vim-sensible#178]
`defaults.vim` use `set display=truncate`, and `set display+=lastline` doesn't make any effect when added after it.

It should probably be replaced with the following:

```viml
" If the value of `display` is `truncate`, do nothing.
" Otherwise, i.e. if the value of `display` is `uhex` or empty, add `lastline`.
if &display != 'truncate'
  set display+=lastline
endif
```

**Comment by tpope** [comment]
Maybe, but if it doesn't actively hurt anything, I'm inclined to let sleeping dogs lie.
