### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by licarezende** [tpope/vim-sensible#181]
Oh no!

Unable to access 'https://tpope.io/vim/sensible.git/': SSL certificate problem: certificate has expired

**Comment by tpope** [comment]
I'm seeing this:

```
Issued On	Monday, January 10, 2022 at 12:34:03 PM
Expires On	Sunday, April 10, 2022 at 1:34:02 PM
```

Can you tell me what date's you're seeing?

**Comment by hholst80** [comment]
Man in the middle  enterprise root snoop cert maybe expired... 😄
