### ISSUE TITLE
Usage of :redir causes ≈10x perf regression when loading vim-sensible

### ISSUE THREAD

**Issue by 0az** [tpope/vim-sensible#186]
When running `nvim -u sensible.vim --startuptime profile.txt` and comparing `8e274c23` against `16283468` (HEAD), there's a 10x load time regression when sourcing vim-sensible.

With execute():
```
007.610  001.433  001.069: sourcing sensible-execute.vim
```

With redir:
```
014.781  010.228  009.955: sourcing sensible.vim
```

On my older (work) machine, it's a more significant difference, though I don't have that profile handy.

**Comment by tpope** [comment]
It might be faster to do 1 big `redir` rather than 13. Feel free to investigate further. At 9 milliseconds of savings, I could not care less about pursing this myself.

**Comment by tpope** [comment]
I overlooked the `execute()` speed improvement. I'm okay to use that conditionally if available.
