### ISSUE TITLE
New to vim - Followed instructions but nothing

### ISSUE THREAD

**Issue by Shaqiloheal** [tpope/vim-sensible#189]
Installed as per instructions however nothing has changed on my vim.

![Screenshot from 2023-12-30 13-05-17](https://github.com/tpope/vim-sensible/assets/95550358/7a6c2863-9693-4502-95a1-e0776feaf656)

**Comment by tpope** [comment]
If you don't have a vimrc, Vim will load `defaults.vim` which is very similar. So you might not spot anything obviously different. One thing that is different is `:set sidescrolloff?`: if it's `2`, then `sensible.vim` is working as expected.
