### ISSUE TITLE
:autoread can be dangerous if you don't notice when it reloads

### ISSUE THREAD

**Issue by fenugrec** [tpope/vim-sensible#196]
I prefer the warning letting me know a file changed outside of vim and offering me to reload. Maybe it was on purpose, maybe not. If I'm not paying attention and it reloads, that will cost me time down the road.

**Comment by tpope** [comment]
>  If I'm not paying attention and it reloads, that will cost me time down the road.

Why?

**Comment by fenugrec** [comment]
e.g. I edited something in the file, didn't save, then do some unorthodox git manoeuvres (which trigger an autoreload), then continue editing, I lose the first edits. My fault for not saving, of course, but this is IMO unnecessary danger.
Feel free to close, obviously, but surely I can't be the only one to run into this kind of situation ?

**Comment by tpope** [comment]
> e.g. I edited something in the file, didn't save

`'autoread'` won't throw away changes.

```vimhelp
'autoread' 'ar'		boolean	(default on)
			global or local to buffer |global-local|
	When a file has been detected to have been changed outside of Vim and
	it has not been changed inside of Vim, automatically read it again.
```
