### ISSUE TITLE
Objectionable settings

### ISSUE THREAD

**Issue by richo** [tpope/vim-sensible#20]
Well, you _did_ say if anyone objects to anything...

`incsearch` breaks the "install on remote servers" usecase imo, in the case of a crap connection or a machine swapping violently, vim trying to redraw the screen on each keystroke is a pain. Also, the option has bugged me since day 1, but that's a more scientific objection than simply "it bugs me".

`fileformats+=mac` I'm assuming this doesn't actually set the line ending to CR like the first docs I found suggest, since even OSX doesn't do this any more. Surely if you're going to pick a horse in this race, unix is the right default?

`smartcase` I'm still not sure this is necessarily expected behaviour. If I search for a lowercase identifier I expect to only see lowercase matches, that could just be me though. I foresee the usecase for this config being almost exclusively code, and not free text which I generally assumed was the main usecase for smartcase.

**Comment by sedm0784** [comment]
I just [discovered another person that doesn't like `incsearch`](https://vi.stackexchange.com/questions/15291/search-not-to-work-on-each-new-char). So now there are at least two of you!

**Comment by richo** [comment]
DOZENS OF US
