### ISSUE TITLE
Proposal: break undo for <C-u>

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-sensible#28]
CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo, so that you can undo CTRL-U without undoing what you typed before it.

```
inoremap <C-U> <C-G>u<C-U>
```

(This is from [vimrc_example.vim](http://vim.cybermirror.org/runtime/vimrc_example.vim), so many people may already have it set.)

**Comment by pkoch** [comment]
Would it make sense to put a link right before that line? I had to search for it, I imagine many others do as well.

**Comment by tpope** [comment]
Link to what? I'd lean towards a terse inline explanation if anything.

**Comment by josephholsten** [comment]
How do we feel about the ticket message as a `terse inline explanation`:
```
CTRL-U in insert mode deletes a lot. Use CTRL-G u to first break undo, so that you can undo CTRL-U without undoing what you typed before it.
```
