### ISSUE TITLE
more intuitive visual-block mode

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-sensible#59]
I'm just going to throw this out there:

`set virtualedit=block "Allow virtual editing in Visual block mode.`

I can see why the default is useful, but I wonder if this is a better default.

**Comment by Asheq** [comment]
@tpope @justinmk Has there ever been a discussion on this? I'm curious why anyone would *not* set `virtualedit` to `block`.

**Comment by justinmk** [comment]
I side-stepped the issue because I use the `yov` map from unimpaired: https://github.com/tpope/vim-unimpaired/commit/49df740f8e0bc64a14557058620a6b6723eb68e6
