### ISSUE TITLE
set linebreak

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-sensible#63]
Anyone opposed to this? Seems like a universally desirable default.

```
set linebreak

	If on Vim will wrap long lines at a character in 'breakat' rather
	than at the last character that fits on the screen. 
```

Note that this doesn't turn hard-wrapping on, it just makes hard-wrapping and `gq` behave differently.

**Comment by chdiza** [comment]
`linebreak` is bad for code, since it often makes it appear that there are spaces where in fact there are none.

Merits or demerits aside, this option seems like an obvious case of what should NOT be in a neutral vimrc.

**Comment by tpope** [comment]
Yeah it's not going to happen. It might make a good addition to unimpaired.vim's option toggles.
