### ISSUE TITLE
'set autoread' -- I have reservations.

### ISSUE THREAD

**Issue by docwhat** [tpope/vim-sensible#64]
I'm not fond of `set autoread`.  I'm sort of torn, since sometimes I would want it turned on.

I had it on in Emacs when I used it as my primary editor, so I'm not sure why I dislike it in vim.  Maybe because vim`s prompt is less obnoxious.

I've had work saved by not having it autoread a buffer.  Not often, but often enough that dealing with the prompt asking if I should load or not isn't a huge problem.  Though I wish it would give me a diff or something.

As I said, I'm sort of torn...but I think for "sensible" defaults, it should be off.

**Comment by hobarrera** [comment]
I think `autoread` should be mentioned in the readme (as well as the fact that it can be undone).

Otherwise, it just *feels* like there's data loss at time thans to vim-sensible, and I don't think it's very obvious that `undo` will also undo an autoread.

**Comment by pkoch** [comment]
Fully agree. If not in the README (might be a bit too much real estate, I get that), at least a comment in the source.

**Comment by tpope** [comment]
I'd be okay adding a bullet for it in the features section.
