### ISSUE TITLE
encoding=utf-8 breaks alt key on Windows

### ISSUE THREAD

**Issue by tiesmaster** [tpope/vim-sensible#69]
I noticed that vim-sensible broke my alt-key mappings, and after a little bit of debugging, I found out that it was caused by the encoding option. See also my post in the vim mailinglist [1].

Although, setting encoding to utf-8 really makes sense, it's questionable it should be in a plugin, since it could break alt-mappings defined earlier.

Maybe, setting encoding to utf-8 doesn't belong in this plugin, or alternatively, this shouldn't be a plugin, but rather something like pathogen, to be invoked manually.

[1] http://article.gmane.org/gmane.editors.vim/114896

**Comment by justinmk** [comment]
@xqin This [vim_dev thread](https://groups.google.com/d/msg/vim_dev/up1KslPRGzk/vfn0QWLKtacJ) supports what I said above:

> 4) It _is_ possible to set 'encoding' to UTF-8 in the vimrc, with 
> appropriate safeguards, if used at the right spot in the "chronology" of 
> successive actions (and in particular, before defining mappings or 
> setting string option values including characters above 0x7F).
