### ISSUE TITLE
Sensible blocks highlight configs, requires re-sourcing vimrc to enable them

### ISSUE THREAD

**Issue by benbarbour** [tpope/vim-sensible#74]
See: http://unix.stackexchange.com/questions/74758/why-does-vim-only-activate-my-highlight-configuration-after-i-source-my-vimrc-m

I don't fully understand the t_Co line (reading documentation now), but it would be nice if this didn't happen, or at least if there was a workaround for it.

**Comment by tpope** [comment]
Stumbling on to this several years later, the issue that is now readily apparent is that `highlight` declarations are fragile and cannot by reliably set from your vimrc. Sensible's `'t_Co'` meddling will destroy them, but so will changing color schemes, or `:set background=dark`. See `:help syncolor` for the right way to do things.
