### ISSUE TITLE
set lazyredraw

### ISSUE THREAD

**Issue by bruno-** [tpope/vim-sensible#78]
`set lazyredraw`

I'm not aware of any downside to setting this, so bringing it up.

**Comment by mtglsk** [comment]
Just to make some comments, because this setting causes issues in some terminals.

This makes it not flicker in all libvte based terminals (gnome-terminal, sakura, terminator, etc.) on ^L:

    if maparg('<C-L>', 'n') ==# ''
      nnoremap <silent> <C-L> :set lz!<CR>:nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>:set lz!<CR>
    endif

And this seems to help with missing statusline when entering vim:

    autocmd VimEnter * set nolazyredraw lazyredraw

**Comment by sassanh** [comment]
I experience rare glitches in `Neovim` on `ITerm2` with `lazyredraw` on (both latest versions). So I guess it may be harmful for some people (maybe few).

**Comment by justinmk** [comment]
@sassanh We'd prefer to (eventually) fix the bug in Nvim rather than ask sensible to care about our regression. However, you actually don't need sensible.vim in Nvim, we've adopted 95% of its options in a very careful manner. https://github.com/neovim/neovim/issues/2676

**Comment by sassanh** [comment]
@justinmk I don't use sensible.vim and never used it (I use lots of tpope's plugins, but don't have a use case for this one, specially considering I'm using nvim.) I just found this thread here: http://vi.stackexchange.com/questions/9776/ability-to-make-vim-run-commands-in-background-and-only-show-the-final-result-on/9780?noredirect=1#comment17078_9780 while discussing another issue and wanted to notice it here. Btw it'll be great if you manage to fix the bug in Nvim and use lazyredraw by default. I appreciate all the good job you do on Nvim.

**Comment by sitilge** [comment]
By setting `lazyredraw` solved my issue with slow scrolling on `neovim v0.2.0`.

**Comment by tonyvitonis** [comment]
FWIW, `set lazyredraw` made my status line invisible on the first display of `vimdiff`.
