### ISSUE TITLE
Please don't set wildmenu

### ISSUE THREAD

**Issue by jpflouret** [tpope/vim-sensible#81]
I think whether to set `wildmenu` or not is a personal choice that should not be included in vim-sensible.

**Comment by mtglsk** [comment]
Afaik you can use both completions, for example `set wildmode=longest,list` for bash style and when `wildmenu` is set then you can use shift-tab on the command line when you need / want zsh like completion. I think `set wildmode=longest:full` is a good compromise between the two.

**Comment by bukzor** [comment]
`list` seems a bit gross, to me.  I've been using `wildmode=longest:full`.
