### ISSUE TITLE
fileformats+=mac and long lines

### ISSUE THREAD

**Issue by hcraT** [tpope/vim-sensible#87]
Hi,
I would like to report a problem that probably doesn't apply to many. If open a "unix formatted" file with at least one line that is equal to or longer than 8192 chars with fileformats set to "unix,dos,mac" Vim opens it as it would be a file with a unique line.

I think that is probably safe to keep the "fileformats+=mac" but I reported this problem so you are aware about it. If I'm able I will try to hunt down the bug in Vim and report it upstream.

Best regards,
Tarcisio.

P.S. A bit off topic but I would like to thank you for the great plugins you develop!

**Comment by chrisbra** [comment]
I cannot reproduce this issue. Please, if you can reproduce this starting from `vim -u NONE -N --cmd ':set ffs=unix,dos,mac' file` please mention this at the vim-dev mailinglist. Then this can likely be fixed.

**Comment by hcraT** [comment]
I can reproduce the problem with this command:
<code>
function gen_str { perl -e '@l = "a".."z"; print(join("", map($l[int(rand(@l))], 0..('$1' - 1))),"\n") for 0..9'; }; vim -O2 -u NONE -N --cmd ':set ffs=unix,dos,mac' <( gen_str 8191) <( gen_str 8192)
</code>
I will send the same command line to the vim-dev mailing list so they can fix this.

**Comment by chrisbra** [comment]
Hi hcraT!

On Fr, 13 Feb 2015, hcraT wrote:

> I can reproduce the problem with this command:
> <code>
> function gen_str { perl -e '@l = "a".."z"; print(join("", map($l[int(rand(@l))], 0..('$1' - 1))),"\n") for 0..9'; }; vim -O2 -u NONE -N --cmd ':set ffs=unix,dos,mac' <( gen_str 8191) <( gen_str 8192)
> </code>
> I will send the same command line to the vim-dev mailing list so they can fix this.

Thanks. This looks in fact like issue 77. So I'll merge those two 
issues. In fact, using the patch from that 
[issue](https://code.google.com/p/vim/issues/detail?id=77) it works 
okay.

Best,
Christian
-- 
Bin ich meinem Amte in der Tat nicht gewachsen, so ist der Chef zu
tadeln, der es mir anvertraut.
		-- Friedrich Schiller

**Comment by hcraT** [comment]
Perfect. I think that this issue can be closed.
If anyone encounters this problem it can be temporarily solved by adding:
<pre>
set fileformats="unix,dos"
</pre>
in the .vimrc after the sourcing of vim-sensible.

Best regards,
hcraT

**Comment by tpope** [comment]
For the record, it's been a long time since I've seen a file in mac file format, so I'm not super attached to keeping this around.

**Comment by hcraT** [comment]
I think I've never opened a file in mac format but I don't think many people will encounter this problem (very long lines). Anyway this could be a solution if other users don't need mac fileformat compatibility.

**Comment by netei** [comment]
> For the record, it's been a long time since I've seen a file in mac file format, so I'm not super attached to keeping this around.

I just got the same problem today, when having files with long line and that could be reproduced with the following vimrc 

```
set nocompatible              " be iMproved, required

" set the runtime path to include plug.vim
if has('vim_starting')
  " Required:
  source ~/.vim/autoload/plug.vim
endif

call plug#begin()
Plug 'tpope/vim-sensible'
call plug#end()
```

It can also be reproduced with just `set fileformats+=mac` so I guess it is a bug in vim, but it would be great to remove that either way.
