### ISSUE TITLE
Setting listchars eol to empty string makes selecting empty lines invisible

### ISSUE THREAD

**Issue by mtglsk** [tpope/vim-sensible#91]
Simple test, use this:

`set listchars+=eol:$`

Then you can see the visual selection on empty lines.

With default sensible settings you can't see the selection. With `set list` the dollar would look ugly though.

**Comment by Greduan** [comment]
Is it not good to be able to select empty lines? I'm not sure why this is an issue. Could you elaborate?

I expect this to be the case and I'd find it weird if I couldn't see when I select an empty line...

**Comment by tpope** [comment]
Well that's unfortunate. One compromise could be to set it to whitespace: `:set listchars+=eol:\ `. But this has the side effect of showing an extra blank line after lines with the exact width of the window.

**Comment by mtglsk** [comment]
Here is a screenshot that makes the issue more visible (on the left the default, on right with `set listchars+=eol:$`)
![vim](https://cloud.githubusercontent.com/assets/10101321/6191387/3d4ab11a-b3a9-11e4-82e4-c8a70b76f3c6.png)

**Comment by tpope** [comment]
Yeah I see the problem. I just think the solutions are worse. Might this qualify as a Vim bug?

**Comment by chrisbra** [comment]
I would consider a bug. Please file a ticket at the [vim bugtracker](https://code.google.com/p/vim/issues/list) or write to the vim-dev mailinglist.

**Comment by mtglsk** [comment]
I managed to fix this:
    set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+,eol:$
    match Ignore "\n"

The only minus is like tpope said: "showing an extra blank line after lines with the exact width of the window". But now i don't have eye soreing eols everywhere but can see them on visual selection.

**Comment by tpope** [comment]
If this is important to you I guess it's easy enough to set `'listchars'` yourself. I don't plan on changing the existing behavior at this time.
