### ISSUE TITLE
can't override tags using `set tags`

### ISSUE THREAD

**Issue by oryband** [tpope/vim-sensible#94]
```vim
" In $MYVIMRC:
set tags=./.tags;,~/.vim/.vimtags
" OR
setglobal tags=./.tags;,~/.vim/.vimtags
```
After restarting:
```vim
:verbose set tags?
tags=./tags;,./.tags;,~/.vim/.vimtags
        Last set from ~/documents/dotfiles/.vim/bundle/vim-sensible/plugin/sensible.vim
```
As you can see, 
I can't override the tags because *sensible* is doing something aggressive.
I solved this by using a hack:
```vim
augroup ...
    autocmd FileType * set tags=./.tags;,~/.vim/.vimtags
augroup END
```
But this is just a hack.

Any idea how can I `set tags` once and make it permanent?

**Comment by vheon** [comment]
I saw from your dotvim that you're using Vundle. The vimrc is sourced before the plugins, so in your vimrc you `set tags=./.tags;,~/.vim/.vimtags` and then in vim-sensible 

```
if has('path_extra')
  setglobal tags-=./tags tags^=./tags;
endif
```

If you want to override sensible default you should load that before your settings in your vimrc. I do it like [this](https://github.com/vheon/home/blob/master/.vim/vimrc#L117)

**Comment by tpope** [comment]
For this particular case, we can solve the problem by being a bit more conscientious in avoiding duplicates.

**Comment by oryband** [comment]
@tpope I'm sorry, but my output is still the following after updating:
```vim
" .vimrc:
set tags=./.tags;,~/.vim/.vimtags
set globaltags=./.tags;,~/.vim/.vimtags " also tried this to no avail.
```
```vim
:verbose set tags?
tags=./tags;,./.tags;,~/.vim/.vimtags
        Last set from ~/Documents/dotfiles/.vim/bundle/vim-sensible/plugin/sensible.vim
```
@vheon @tpope I couldn't get sensible to be executed before my `.vimrc`, even though I did:
```vim
call vundle#end()
runtime plugin.sensible.vim  " It looks like sensible is sourced at all in this way.
```
Any idea what am I doing wrong?

**Comment by tpope** [comment]
For starters you want `runtime! plugin/sensible.vim` and `setglobal tags`

**Comment by oryband** [comment]
@tpope I used `setglobal tags` and `plugin/sensible.vim`, i just had typos in the previous comment.
It still doesn't work.

This is interfering with xolox/vim-easytags#92 (see issue for explanation).

**Comment by oryband** [comment]
@tpope sorry for asking again, but I would greatly appreciate help on this. I've been fighting this bug for a very long time and it made me a very sad person.
![](http://images5.fanpop.com/image/photos/30700000/sad-kitty-our-wolf-pack-30789040-500-333.jpg)

**Comment by tpope** [comment]
You can check `:echo &runtimepath` before `runtime! plugin/sensible.vim` to make sure it's correct. Also see `:scriptnames` to confirm when sensible.vim is loading.

**Comment by tpope** [comment]
I've decided that if `./tags` has been removed from `'tags'`, that's a good signal we shouldn't do further meddling.
