### ISSUE TITLE
Why is scrolloff set to 1?

### ISSUE THREAD

**Issue by fmoralesc** [tpope/vim-sensible#95]
What is the reason for having `scrolloff` set to 1? In a discussion on the new defaults for neovim, [someone argues against it](https://github.com/neovim/neovim/issues/2676#issuecomment-102783594): 

> I don't see the point of set scrolloff=1.

> It reduces my 'text canvas' (the screen area I can reach without scrolling) by one line at the top and one line at the bottom. There would now be two lines visible on the screen that I can't reach directly any more (H becomes Hk and scrolls the screen). But in Vim, I expect to be in charge of my cursor. I expect H to take me to the very top of the screen.

> I've just checked TextEdit and gEdit, both behave as with scrolloff=0. They don't scroll when there's no need to, only when the cursor would leave the screen. Most editors work this way, don't they?

> I think scrolloff=0 seems like a reasonable default. scrolloff=1 seems ok, too, but the behaviour is slightly less expected (cue Stackoverflow questions 'can't move my cursor to the first line in Neovim!'), and for advanced users perhaps slightly less useful.

I tend to agree with this (specially in regards to the mismatch between moving the cursor and moving the viewport it causes when using H and similar), so I wanted to know your thoughts about it.

**Comment by tpope** [comment]
Based entirely on my personal experience, adding just a single line of mandatory context greatly reduces my need to fiddle with `<C-E>`/`<C-Y>`. If I read you correctly, you are asserting that it causes `H` to move the viewport, but it does not: It changes which line is jumped to. (I agree this is a bit unfortunate, but it is still very predictable, just a bit harder to explain.)

**Comment by tpope** [comment]
I would further add that you are the first person to bring this up, which is saying a lot if you've taken a look at the sort of petty objections people raise. Whether that justifies changing the neovim default, I cannot say. I can say you have the advantage it can still be trivially overridden in a user's own config, unlike for late loading sensible.vim.

**Comment by fmoralesc** [comment]
Thanks for the reply, I can now see your point too (and your last comment is very insightful). While reviewing the defaults in your plugin and in [eigenvim](https://github.com/rht/eigenvimrc), I've sometimes felt it would be nice to know the reasons for having these settings.

As for `scrolloff`, I can see the value in having more context, and it doesn't seem to reduce the number of motions one needs to reach any line, so I guess my initial reaction to this caused by me not being used to this behavior. I was also worried because describing a motion like H implies accounting for the value of `scrolloff`, and there is no indication of this value by default, so I imagine it's a bit surprising from the perspective of a new user (given than many other editors behave differently).

Once again, thanks for your input, it's greatly appreciated.

**Comment by tpope** [comment]
Yeah the new user issue is the problem; that's much more problematic on the neovim side of things than in sensible. At a minimum you would want to adjust the docs to more prominently emphasize that.

**Comment by fmoralesc** [comment]
Btw, messing around this I came up with these:
~~~
noremap <expr> H 'H' . eval('&scrolloff') . '<C-u>'
noremap <expr> L 'L' . eval('&scrolloff') . 'j'
~~~
They feel like a good addition to `scrolloff > 0`.

**Comment by cpenner-va** [comment]
> Btw, messing around this I came up with these:
```
noremap <expr> H 'H' . eval('&scrolloff') . '<C-u>'
noremap <expr> L 'L' . eval('&scrolloff') . 'j'
```
> They feel like a good addition to scrolloff > 0.

These work, but also ruin the notion of absolute location that H and L have, before you could hit H as many times as you want and it will stay on the same line, now it moves the screen each time :P

**Comment by fmoralesc** [comment]
I think the only reason H and L don't behave as in those mappings is someone thought the screen movement was annoying ;) Actually, [I'm pretty sure about it](https://github.com/neovim/neovim/pull/2687#issuecomment-102834197).
